bolao/urls.py
from django.conf.urls import url
from django.contrib import admin
from palpites import views
import instituicoes.views
import usuarios.views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^palpites/$', views.palpites_list, name='palpites'),
    url(r'^instituicoes/$', instituicoes.views.instituicoes_list, name='instituicoes'),
    url(r'^', include('usuarios.urls', namespace='usuarios', app_name='usuarios')),
    url(r'^', include('palpites.urls', namespace='palpites', app_name='palpites')),
    #url(r'^', include('usuarios.urls', namespace='usuarios', app_name='usuarios')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

palpites/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^cadastro-palpites/$', views.cadastro_palpites, name='cadastro-palpites'),
]

palpites/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Palpite(models.Model):
    autor = models.ForeignKey('auth.User', null=True, related_name="palpite")
    title = models.CharField(max_length=20)
    pj1c = models.IntegerField()
    pj1f = models.IntegerField()
    pj2c = models.IntegerField()
    pj2f = models.IntegerField()
    pj3c = models.IntegerField()
    pj3f = models.IntegerField()
    pj4c = models.IntegerField()
    pj4f = models.IntegerField()
    total = models.IntegerField(default=0)

    def __str__(self):
        return self.title

# Create your models here.

palpites/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from .models import Palpite


class PalpiteForm(forms.ModelForm):
	autor = forms.CharField(widget=forms.HiddenInput(), initial="aaa")
	title = forms.CharField(widget=forms.TextInput())
	pj1c = forms.IntegerField()
	pj1f = forms.IntegerField()
	pj2c = forms.IntegerField()
	pj2f = forms.IntegerField()
	pj3c = forms.IntegerField()
	pj3f = forms.IntegerField()
	pj4c = forms.IntegerField()
	pj4f = forms.IntegerField()
	class Meta:
		model = Palpite
		fields = ['title', 'pj1c', 'pj1f', 'pj2c', 'pj2f' , 'pj3c', 'pj3f', 'pj4c', 'pj4f']
		widgets = {
			'autor': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 20}),
			'title': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 20}),
			'pj1c': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 2}),
			'pj1f': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 2}),
			'pj2c': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 2}),
			'pj2f': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 2}),
			'pj3c': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 2}),
			'pj3f': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 2}),
			'pj4c': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 2}),
			'pj4f': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 2})
		}

		

	

palpites/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from palpites.forms import PalpiteForm
from models import Palpite
from .forms import PalpiteForm
from django.contrib.auth.decorators import login_required

from instituicoes.models import Instituicao
from django.contrib.auth.models import User
from usuarios.models import Profile


# Create your views here.

def palpites_list(request):
    autores = User.objects.all().filter(profile__status=True)
    palpites = Palpite.objects.all().filter(autor__in=autores).order_by('-total')
    instituicoes = Instituicao.objects.all()

    #PONTUAÇÃO
    empate_certo = 5
    empate_errado = 3
    placar_certo = 5
    vencedor_certo = 3
    perdedor_certo = 2
    vencedor = 1

    # RESULTADO REAL DOS JOGOS

    rj1c = 2
    rj1f = 2
    rj2c = 2
    rj2f = 1
    rj3c = 2
    rj3f = 3
    rj4c = 0
    rj4f = 0

    vez = 2


    # CÁLCULO DA PONTUAÇÃO
    for palpite in palpites:
    	total = 0

    	pj1c = palpite.pj1c
    	pj1f = palpite.pj1f
        pj2c = palpite.pj2c
        pj2f = palpite.pj2f
        pj3c = palpite.pj3c
        pj3f = palpite.pj3f
        pj4c = palpite.pj4c
        pj4f = palpite.pj4f
    	

    	#CALCULA PONTUACAO


        #-----inicio------#

        if ((rj1c and rj1f) != "?"):

        	if ((pj1c == pj1f)and(rj1c == rj1f)):
        		if ((pj1c == rj1c)and(pj1f == rj1f)):
        			total = total+empate_certo
        		else: 
        			total = total+empate_errado	
        			

        	elif (pj1c > pj1f):
        		if (rj1c > rj1f):
        			if ((pj1c == rj1c)and(pj1f == rj1f)):
        				total = total+placar_certo
        			elif ((pj1c == rj1c)and(pj1f != rj1f)):
        				total = total+vencedor_certo
        			elif ((pj1c != rj1c)and(pj1f == rj1f)):
        				total = total+perdedor_certo
        			else:
        				total = total+vencedor
        		else:
        			total = total


        	else:
        		if (rj1c < rj1f):
        			if ((pj1c == rj1c)and(pj1f == rj1f)):
        				total = total+placar_certo
        			elif ((pj1c == rj1c)and(pj1f != rj1f)):
        				total = total+perdedor_certo
        			elif ((pj1c != rj1c)and(pj1f == rj1f)):
        				total = total+vencedor_certo
        			else:
        				total = total+vencedor
        		else:
        			total = total

            #-----fim------#


            #-----inicio------#
        if ((rj2c and rj2f) != "?"):

            if ((pj2c == pj2f)and(rj2c == rj2f)):
                if ((pj2c == rj2c)and(pj2f == rj2f)):
                    total = total+empate_certo
                else: 
                    total = total+empate_errado 
                    

            elif (pj2c > pj2f):
                if (rj2c > rj2f):
                    if ((pj2c == rj2c)and(pj2f == rj2f)):
                        total = total+placar_certo
                    elif ((pj2c == rj2c)and(pj2f != rj2f)):
                        total = total+vencedor_certo
                    elif ((pj2c != rj2c)and(pj2f == rj2f)):
                        total = total+perdedor_certo
                    else:
                        total = total+vencedor
                else:
                    total = total


            else:
                if (rj2c < rj2f):
                    if ((pj2c == rj2c)and(pj2f == rj2f)):
                        total = total+placar_certo
                    elif ((pj2c == rj2c)and(pj2f != rj2f)):
                        total = total+perdedor_certo
                    elif ((pj2c != rj2c)and(pj2f == rj2f)):
                        total = total+vencedor_certo
                    else:
                        total = total+vencedor
                else:
                    total = total

            #-----fim------#


        if ((rj3c and rj3f) != "?"):

            if ((pj3c == pj3f)and(rj3c == rj3f)):
                if ((pj3c == rj3c)and(pj3f == rj3f)):
                    total = total+empate_certo
                else: 
                    total = total+empate_errado 
                    

            elif (pj3c > pj3f):
                if (rj3c > rj3f):
                    if ((pj3c == rj3c)and(pj3f == rj3f)):
                        total = total+placar_certo
                    elif ((pj3c == rj3c)and(pj3f != rj3f)):
                        total = total+vencedor_certo
                    elif ((pj3c != rj3c)and(pj3f == rj3f)):
                        total = total+perdedor_certo
                    else:
                        total = total+vencedor
                else:
                    total = total


            else:
                if (rj3c < rj3f):
                    if ((pj3c == rj3c)and(pj3f == rj3f)):
                        total = total+placar_certo
                    elif ((pj3c == rj3c)and(pj3f != rj3f)):
                        total = total+perdedor_certo
                    elif ((pj3c != rj3c)and(pj3f == rj2f)):
                        total = total+vencedor_certo
                    else:
                        total = total+vencedor
                else:
                    total = total

            #-----fim------#



        p = Palpite.objects.get(id = palpite.id)
        p.total = total
        p.save()

    	palpite.total = total
        
        i=0
    
    return render(request, 'palpites/palpite_list.html', {'palpites' : palpites, 'instituicoes' : instituicoes, 'i':i})


@login_required
def cadastro_palpites(request):
    form = PalpiteForm(request.POST or None)
    instituicoes = Instituicao.objects.all()
    context = {'form':form, 'instituicoes':instituicoes}
    if request.method == 'POST':
		if form.is_valid():
			palpite = form.save(commit=False)
			palpite.autor = request.user
			palpite.save()
			form.save()

			return redirect('/palpites')
    return render(request, 'palpites/cadastro_palpites.html', context)

palpites/templates/palpites/cadastro_palpites.html
{% extends 'bolao/base.html' %}

{% block content %}
<div class="col-md-3">
</div>
<div class="col-md-6">
    	<form action="{% url 'palpites:cadastro-palpites' %}" class="form-sigin" method="post">
    		{% csrf_token %}
    		<h2>Cadastre seu palpite</h2>
    		{{form.autor}}
    		<br>
    		<label>Nome do seu palpite</label>
    		{{form.title}}
    		{{form.title.error}}
    		<br>
            <table class="tabela_cadastro_palpites">
                <tr>
                
                    <td>Jogo 1</td>
                    <td class="primeiro"><img src="{{ instituicoes.0.image.url }}" title="{{ instituicoes.0.nome_curto }}" width="20" /> </td>
                    <td class="primeiro">{{ instituicoes.0.nome_curto }}</td>
                    <td class="input_placar primeiro">{{form.pj1c}}
                    {{form.pj1c.error}}</td>
                    <td class="versus">X</td>
                    <td class="input_placar">{{form.pj1f}}
                    {{form.pj1f.error}}</td>
                    <td>{{ instituicoes.1.nome_curto }}</td>
                    <td><img src="{{ instituicoes.1.image.url }}" title="{{ instituicoes.1.nome_curto }}" width="20" /></td>
                
                </tr>
            </table>
    		
    		<label>Jogo 2</label><br>
    		{{form.pj2c}}
    		{{form.pj2c.error}} X 
    		{{form.pj2f}}
    		{{form.pj2f.error}}
            <br>
            <label>Jogo 3</label><br>
            {{form.pj3c}}
            {{form.pj3c.error}} X 
            {{form.pj3f}}
            {{form.pj3f.error}}
            <br>
            <label>Jogo 4</label><br>
            {{form.pj4c}}
            {{form.pj4c.error}} X 
            {{form.pj4f}}
            {{form.pj4f.error}}

    		<button class="btn btn-lg btn-primary btn-block" type="submit">Jogar</button>
    	</form>
</div>
<div class="col-md-3">
</div>	
		
{% endblock content %}

palpites/templates/palpites/palpite_list.html
{% extends 'bolao/base.html' %}

{% block content %}

    	<h2>Ranking</h2>
    	<br><br>
        {% for palpite in palpites %}
            
        	<div class="box_tabela">
        		<table class="tabela pontos">
    				<tr>
    				    <th class="nome_palpite">{{ palpite }} &nbsp;({{ palpite.autor }})</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
    				    <th class="total_palpite">{{ palpite.total }}</th>
    				</tr>
                </table>
        		
                <table class="tabela palpites">
            		<tr>
            			<td>Jogo 1</td><td class="primeiro"><img src="{{ instituicoes.0.image.url }}" title="{{ instituicoes.0.nome }}" width="20" /></td><td class="primeiro">{{ instituicoes.0.nome_curto }}</td><td class="placar">{{ palpite.pj1c }}</td><td class="placar">X</td><td class="placar">{{ palpite.pj1f }}</td><td>{{ instituicoes.1.nome_curto }}</td><td><img src="{{ instituicoes.1.image.url }}" title="{{ instituicoes.1.nome_curto }}" width="20" /></td>
            		</tr>
                    <tr>
                        <td>Jogo 2</td><td class="primeiro"><img src="{{ instituicoes.2.image.url }}" title="{{ instituicoes.2.nome }}" width="20" /></td><td class="primeiro">{{ instituicoes.2.nome_curto }}</td><td class="placar">{{ palpite.pj2c }}</td><td class="placar">X</td><td class="placar">{{ palpite.pj2f }}</td><td>{{ instituicoes.3.nome_curto }}</td><td><img src="{{ instituicoes.3.image.url }}" title="{{ instituicoes.3.nome_curto }}" width="20" /></td>
                    </tr>
                    <tr>
                        <td>Jogo 3</td><td class="primeiro"><img src="{{ instituicoes.4.image.url }}" title="{{ instituicoes.4.nome }}" width="20" /></td><td class="primeiro">{{ instituicoes.4.nome_curto }}</td><td class="placar">{{ palpite.pj3c }}</td><td class="placar">X</td><td class="placar">{{ palpite.pj3f }}</td><td>{{ instituicoes.5.nome_curto }}</td><td><img src="{{ instituicoes.5.image.url }}" title="{{ instituicoes.5.nome_curto }}" width="20" /></td>
                    </tr>
                    <tr>
                        <td>Jogo 4</td><td class="primeiro"><img src="{{ instituicoes.6.image.url }}" title="{{ instituicoes.6.nome }}" width="20" /></td><td class="primeiro">{{ instituicoes.6.nome_curto }}</td><td class="placar">{{ palpite.pj4c }}</td><td class="placar">X</td><td class="placar">{{ palpite.pj4f }}</td><td>{{ instituicoes.7.nome_curto }}</td><td><img src="{{ instituicoes.7.image.url }}" title="{{ instituicoes.7.nome_curto }}" width="20" /></td>
                    </tr>
            		
                    


                    		
		        </table>

		    </div>
		{% endfor %}
		<div class="clear"><br><br><br><br><br><br></div>
{% endblock content %}