bolao/urls.py
from django.conf.urls import url
from django.contrib import admin
from palpites import views
import instituicoes.views
import usuarios.views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^palpites/$', views.palpites_list, name='palpites'),
    url(r'^instituicoes/$', instituicoes.views.instituicoes_list, name='instituicoes'),
    url(r'^', include('usuarios.urls', namespace='usuarios', app_name='usuarios')),
    url(r'^', include('palpites.urls', namespace='palpites', app_name='palpites')),
    #url(r'^', include('usuarios.urls', namespace='usuarios', app_name='usuarios')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^cadastro/$', views.cadastro, name='cadastro'),
	url(r'^boleiros/$', views.boleiros, name='boleiros'),
	url(r'^login/$', views.do_login, name='login'),
	url(r'^$', views.do_login, name='index'),
	url(r'^logout/$', views.do_logout, name='logout'),
]

usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from PIL import Image

from django.db.models.signals import post_save
from django.dispatch import receiver

from random import choice
from django.utils.translation import ugettext_lazy as _


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    telefone = models.IntegerField(blank='True', null='True', default='99999999')
    avatar = models.ImageField(upload_to='avatar', blank='True', null='True')
    status = models.BooleanField(default=False)



def set_token(self):
    self.token = ''.join([choice('abcdefghijklmnopqrstuvwxyz0123456789') for i in range(15)])




def save(self, *args, **kwargs):
    super(Profile, self).save(*args, **kwargs)
    self.set_token()

usuarios/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile

from django.utils.translation import ugettext_lazy as _

class UserModelForm(forms.ModelForm):
	User._meta.get_field('first_name').blank = False
	User._meta.get_field('last_name').blank = False
	User._meta.get_field('email').blank = False
    
	
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password']
		widgets = {
			'username': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 20}),
			'first_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 30}),
			'last_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 30}),
			'email': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
			
			'password': forms.PasswordInput(attrs={'class': 'form-control', 'maxlength': 30})
		}

		error_messages = {
			'username': {
				'required': 'Este campo é obrigatório'
			},
			'first_name': {
				'required': 'Este campo é obrigatório'
			},
			'last_name': {
				'required': 'Este campo é obrigatório'
			},
			'email': {
				'required': 'Escreva um e-mail válido'
			},
			'password': {
				'required': 'Este campo é obrigatório'
			}
		}



	def save(self, commit=True):
		user = super(UserModelForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password'])
		if commit:
			user.save()
		return user





class ProfileForm(forms.ModelForm):
	Profile._meta.get_field('telefone').blank = False

	class Meta:
	    model = Profile
	    fields = ('telefone', 'avatar')
	    exclude = ('user',)

usuarios/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from usuarios.forms import UserModelForm
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from palpites.models import Palpite
from .forms import ProfileForm

from .models import Profile

from django.template.context_processors import csrf

def cadastro(request):
	form = UserModelForm(request.POST or None)
	form2 = ProfileForm(request.POST, request.FILES, prefix='profile')
	context = {'form':form, 'form2':form2}
	if request.method == 'POST':
		if form.is_valid() and form2.is_valid():
			user = form.save()
			

			#create entry for UserProfile (extension of new_user object)      
			profile = form2.save(commit = False)
			profile.user = User.objects.get(username=request.POST['username'])
			profile.save()
			sucesso = "Parabéns! Você foi cadastrado com sucesso, efetue o login para entrar em campo."
			return render(request, '/login')
	else:
		form = UserModelForm(prefix = "user")
		form2 = ProfileForm(prefix = "profile")
		c = {
			'form':form,
			'form2':form2,
			}
		c.update(csrf(request))
	return render(request, 'usuarios/cadastro.html', context)

# Create your views here.
@login_required
def boleiros(request):
	boleiros = User.objects.all().filter(profile__status=True)
	return render(request, 'usuarios/boleiros.html', {'boleiros' : boleiros})


def do_login(request):
	if request.method == 'POST':
		user = authenticate(username=request.POST['username'], password=request.POST['password'])
		if user is not None:
			login(request, user)
			return redirect('/cadastro')
	boleiros = User.objects.all()
	palpites = Palpite.objects.all()
	return render(request, 'usuarios/login.html', {'boleiros' : boleiros, 'palpites' : palpites})

@login_required
def do_logout(request):
	logout(request)
	boleiros = User.objects.all()
	palpites = Palpite.objects.all()
	return redirect('/login')









@login_required

def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('settings:profile')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profiles/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

usuarios/templates/usuarios/boleiros.html
{% extends 'bolao/base.html' %}

{% block content %}
	
	    <h2>Boleiros</h2>
	    <h4>Somos  ({{ boleiros.count }}) no total</h4>

		<table class="tabela">
				<tr>
					<th>Avatar</th>
					<th>Nome</th>
					<th>Username</th>
					<th>Telefone</th>
					<th>Status</th>
				</tr>
			   
				{% for boleiro in boleiros %}
					
				<tr>
					<td class="segundo_td"><img src="{{ BASE_URL }}/media/{{ boleiro.profile.avatar }}" width="20"></td>
					<td class="primeiro_td">{{ boleiro.first_name }}</td>
					<td class="segundo_td">{{ boleiro.profile.user }}</td>
					<td class="segundo_td">{{ boleiro.profile.telefone }}</td>
					<td class="segundo_td">{{ boleiro.profile.status }}</td>
				</tr>

				{% endfor %} 
				


		
		</table>



	
		
{% endblock content %}

usuarios/templates/usuarios/cadastro.html
{% extends 'bolao/base.html' %}

{% block content %}

{% if user.is_authenticated %}
   
    <div class="col-md-12">
        <h2>Você está logado(a), segue o jogo!</h2>
    </div>  
    
{% else %}

<div class="col-md-4">
</div>
<div class="col-md-4">
    	<form action="{% url 'usuarios:cadastro' %}" class="form-sigin" method="post" enctype="multipart/form-data">
    		{% csrf_token %}
    		<h2>Por favor, cadastre-se</h2>
    		{{ form.as_p }}
            <label>Telefone</label>
            {{ form2.telefone }}
            {{ form2.telefone.error }}
            <label>Avatar</label>
            {{ form2.avatar }}
            {{ form2.avatar.error }}
    		<br><button class="btn btn-lg btn-primary btn-block" type="submit">Jogar</button>
    	</form>
</div>
<div class="col-md-4">
</div>	
{% endif %}	
{% endblock content %}

usuarios/templates/usuarios/cadastro_success.html
{% extends 'bolao/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <h2>Você está logado(a), segue o jogo!</h2>
{% else %}

<div class="col-md-4">
</div>
<div class="col-md-4">
    	<h2>PARABÉNS!! Você foi cadastrado com sucesso.</h2>
</div>
<div class="col-md-4">
</div>	
{% endif %}	
{% endblock content %}

usuarios/templates/usuarios/login.html
{% extends 'bolao/base.html' %}

{% block content %}


{% if user.is_authenticated %}
    <h2>Você está logado(a), segue o jogo!</h2>
{% else %}
<div class="col-md-4">

</div>
<div class="col-md-4">
        <form action="{% url 'usuarios:login' %}" class="form-sigin" method="post">
            {% csrf_token %}
            <h2 class="form-sigin-heading col-md-14">Entrar no jogo</h2>
            
            <div class="form-group">
                <div class="col-md-14">
                    <input type="text" name="username" class="form-control" placeholder="Nome de usuário">
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-14">
                    <input type="password" name="password" class="form-control" placeholder="senha">
                </div>
            </div>
            
            <br><button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
        </form>

        <br><br>
        <p>Ja temos <strong>{{ boleiros.count }}</strong> boleiros cadastrados, que fizeram um total de <strong>{{ palpites.count }}</strong> palpites</p>
</div>
<div class="col-md-4">
</div>

{% endif %} 




	
		
{% endblock content %}

usuarios/templates/usuarios/login_error.html
{% extends 'bolao/base.html' %}

{% block content %}
<div class="col-md-4">
</div>
<div class="col-md-4">
    	Login incorreto, tente novamente <a href="{% url 'login' %}"></a>
</div>
<div class="col-md-4">
</div>


	
		
{% endblock content %}